item {
    id: 1
    name: 'paper'
}

item {
    id: 2
    name: 'cap'
}

item {
    id: 3
    name: 'tape'
}

item {
    id: 4
    name: 'orange'
}
item {
    id: 5
    name: 'drink'
}
item {
    id: 6
    name: 'straw'
}